### ISSUE TITLE
Neighborhood object 

### ISSUE THREAD

**Issue by Kandroodi** [Kandroodi/WaterSystem#24]
Add neighborhood object with two fields: name and an input to define the polygon on the map (A way to relate neighborhood object to a polygon).

**Comment by Peter-J-B** [comment]
Neighbourhood should also have a link to city so that the user can specify which city each neighbourhood is in. 

We would like the name of each neighbourhood to be numbered by city so, for example, 'Cairo 1' 'Cairo 2' 'Cairo 3' or 'Baghdad 1' 'Baghdad 2'. Would it be easy to make it so that the user just chooses the city and the number and prevent duplicate neighbourhoods from being created?

For the polygon, the user should be able to upload a shapefile which then defines the extent of the neighbourhood on the map.

**Comment by Kandroodi** [comment]
The neighborhood object is added.
