### ISSUE TITLE
numbers used more than once

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#92]
Numbers appear to be used twice if you are working on two entries at the same time, so now we have to installations numbered 0012... It now happened when one person was making two entries at the same time, which is of course something that can be fairly easily avoided, but if more than one person is working in the database at the same time, this will likely cause problems. Can the system be made so that each number can only be used once?

**Comment by josephinevdbent** [comment]
correction: three people were in it and now we have four numbers 0012.

**Comment by Kandroodi** [comment]
The number at the end of the name will be the same if you start entering a new entry before saving the previously opened one. It can also happen if two (or more) people working on entries of an object (e.g. installation) at the same time and open a new form before the other save the previous one. Because the number indicates that how many entries have been saved in the database, so before saving the previous one, it can't be counted. 
A simple solution for this is to save your form immediately after you opened it then continue editing the form.

**Comment by josephinevdbent** [comment]
alright, thanks!

**Comment by Kandroodi** [comment]
Does it solve the problem, or we need to have another solution for that?

**Comment by josephinevdbent** [comment]
It's not ideal, but we'll manage ;)

**Comment by Kandroodi** [comment]
Yes, I know.
As you see now, if you save 3 installations with number 0012, the next one will be 0015. So, it is also possible to rename two of the to 0013 and 0014 later.

**Comment by josephinevdbent** [comment]
ok perfect!
